-- ═══════════════════════════════════════════════════════════════════════════
-- INC-3130 · HOME DENT — חבילה A1: סכמה, מילונים, אבטחה, אחסון, קליטת טופס
-- אפיון: "HOME DENT — מערכת פרסום וניהול נכסים דנטליים / 25.08.2026"
--
-- מסלול מהיר (אושר 26.08.2026): דף הנכס מוגש בתבנית קבועה אחת, ולכן
-- פונקציות הפרסום נכנסות כאן ולא ממתינות לעורך הבלוקים. page_config נשאר
-- בסכמה ריק — כשעורך הבלוקים ייבנה, הוא לא ידרוש מיגרציה נוספת ולא ייגע
-- בנכסים שכבר פורסמו.
--
-- מה כלול:      6 טבלאות, מילון + זריעה, טריגרים, RLS, הרשאות, דליי אחסון,
--               2 RPC ציבוריים (הגשת נכס, השארת פרטים),
--               ו-6 RPC אדמין (בנייה, תצוגה מקדימה, פרסום, עדכון, הסרה, הארכה).
--
-- 6 טבלאות: dental_assets · _offers · _images · _publications · _inquiries
--           · dict_dental_options.
-- מה שירד מ-13: שש טבלאות מילון אוחדו לאחת (עמודות מערך לא יכולות להחזיק
-- FK, ולכן ההפרדה לא קנתה שלמות נתונים); היסטוריית ההארכות הפכה לעמודת
-- jsonb; ורישום שדות הפרסום נדחה ל-A2 יחד עם הצרכן שלו.
-- מה לא כלול:   עורך הבלוקים עצמו (חבילה C). הסכמה מוכנה לו.
--
-- אין בקובץ הזה: customer_visibility · payment_status · חוזים · חישוב עמלה.
-- הם נמחקו מהאפיון במפורש (§77) ואין להחזירם.
-- ═══════════════════════════════════════════════════════════════════════════

begin;

-- ───────────────────────────────────────────────────────────────────────────
-- 0. עזרי בסיס
-- ───────────────────────────────────────────────────────────────────────────

-- קוד הנכס נוצר מ-sequence ולא מ-max()+1. job_code עושה max()+1 עם לולאת
-- התנגשות ואינו בטוח לתחרות; sequence הוא לא-טרנזקציוני ולכן בטוח בהגדרה.
-- פערים במספור לגיטימיים — הקוד הוא מזהה, לא מונה.
create sequence if not exists public.dental_asset_code_seq as bigint start 1;

create or replace function public.hd_touch_updated_at()
returns trigger language plpgsql
set search_path = '' as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- ───────────────────────────────────────────────────────────────────────────
-- 1. מילון אחד לכל אפשרויות הנכס, עם עמודת קבוצה.
--    לא שש טבלאות: עמודות מערך (equipment_ids bigint[]) אינן יכולות להחזיק
--    מפתח זר בפוסטגרס, ולכן הפרדה לטבלאות לא קונה שום שלמות נתונים.
--    id הוא GENERATED BY DEFAULT ולא ALWAYS — INC-3127: ALWAYS שובר upsert().
-- ───────────────────────────────────────────────────────────────────────────
create table if not exists public.dict_dental_options (
  id         bigint generated by default as identity primary key,
  group_key  text not null,
  name       text not null,
  sort_order smallint not null default 0,
  is_active  boolean  not null default true,
  created_at timestamptz not null default now(),
  constraint hd_opt_group_ck check (group_key in
    ('accessibility','premises','imaging','equipment','services','sale_includes')),
  constraint hd_opt_uq unique (group_key, name)
);
create index if not exists hd_opt_group_idx on public.dict_dental_options (group_key, sort_order);

insert into public.dict_dental_options (group_key, name, sort_order) values
  ('accessibility','חניה ברחוב',1),('accessibility','חניון ציבורי קרוב',2),
  ('accessibility','חניה פרטית',3),('accessibility','חניה לנכים',4),
  ('accessibility','תחבורה ציבורית',5),('accessibility','רכבת / רכבת קלה',6),
  ('accessibility','נגישות לכיסא גלגלים',7),('accessibility','מעלית',8),

  ('premises','חדר קבלה / המתנה',1),('premises','משרד',2),('premises','מטבחון',3),
  ('premises','שירותים',4),('premises','כניסה נפרדת',5),('premises','מרפסת',6),
  ('premises','פטיו',7),('premises','גינה',8),('premises','חדר סטריליזציה',9),
  ('premises','מעבדה',10),('premises','חדר צילום',11),('premises','מחסן',12),
  ('premises','תשתית להרדמה כללית',13),

  ('imaging','רנטגן',1),('imaging','מכשיר פנורמי',2),('imaging','מכשיר סיטי (CBCT)',3),
  ('imaging','סנסור דיגיטלי / חיישן רנטגן',4),('imaging','מערכת צילום אינטרה־אוראלית',5),
  ('imaging','סורק אינטראוראלי',6),('imaging','סורק פלטה פוספורית דיגיטלי',7),
  ('imaging','סורק פנים 3D',8),

  -- איחוד שתי הקבוצות הכפולות שהיו בטופס Fillout (§28)
  ('equipment','אוטוקלב',1),('equipment','סטריליזטור יבש',2),
  ('equipment','מכשיר להלחמת שקיות סטריליזציה',3),('equipment','אמבטיה אולטרסונית',4),
  ('equipment','יחידה דנטלית',5),('equipment','כיסא רופא',6),('equipment','כיסא סייעת',7),
  ('equipment','טורבינות',8),('equipment','מדחס (קומפרסור)',9),
  ('equipment','מערכת ואקום (סקשן)',10),('equipment','מכשיר לייט קיור',11),
  ('equipment','סקיילר',12),('equipment','מכשיר פרופיג׳ט',13),('equipment','מכשיר סאנבלסט',14),
  ('equipment','מכשיר הלבנה',15),('equipment','מנוע השתלות / פיזיו־דיספנסר',16),
  ('equipment','מכשיר אנדו / מנוע אנדודונטי',17),('equipment','מכשיר פנטמיקס',18),
  ('equipment','מכשיר אינדוקציה',19),('equipment','מכשיר פלזמה קרה',20),
  ('equipment','אפליקטור דיגיטלי',21),('equipment','מחרטה',22),
  ('equipment','מכשיר ואקום להכנת סדים',23),('equipment','ציוד ומכשור ידני',24),

  -- "חניה" יושבת בנגישות בלבד ולא כאן, כדי שלא תופיע פעמיים (אושר 26.08.2026)
  ('services','שירותי ניקיון',1),('services','שירותי מזכירות / קבלה',2),
  ('services','סייעת רופא שיניים',3),('services','שירותי סטריליזציה',4),
  ('services','שימוש בציוד המרפאה',5),('services','שימוש בציוד דימות',6),
  ('services','מעבדה / שירותי מעבדה',7),('services','אינטרנט ותקשורת',8),
  ('services','שירותי משרד',9),('services','חשמל ומים כלולים',10),

  ('sale_includes','ציוד ומכשור',1),('sale_includes','ריהוט',2),
  ('sale_includes','פעילות המרפאה',3),('sale_includes','מוניטין',4),
  ('sale_includes','מאגר מטופלים',5),('sale_includes','שם / מותג המרפאה',6),
  ('sale_includes','העברת עובדים',7)
on conflict (group_key, name) do nothing;

-- ───────────────────────────────────────────────────────────────────────────
-- 2. רישום השדות לפרסום — נדחה ל-A2.
--    הוא משרת את hd_build_publication_payload, שנכתב רק אחרי שמבנה
--    הבלוקים ייסגר בחבילה C. אין טעם ליצור אותו לפני הצרכן שלו.
-- ───────────────────────────────────────────────────────────────────────────

-- ───────────────────────────────────────────────────────────────────────────
-- 3. dental_assets
-- ───────────────────────────────────────────────────────────────────────────
create table if not exists public.dental_assets (
  id                    uuid primary key default gen_random_uuid(),
  asset_code            text not null default ('HD' || lpad(nextval('public.dental_asset_code_seq')::text, 4, '0')),
  source                text not null default 'public_form',

  -- שכבה א' — מקור הלקוח. מוקפא בטריגר, לא נדרס לעולם (אפיון §41)
  submission_snapshot   jsonb,
  submission_token      uuid,
  source_page           text,
  source_url            text,

  workflow_status       text not null default 'new',
  publication_state     text not null default 'draft',

  -- בחירת השירות. terms_accepted_at נקבע ב-now() בתוך ה-RPC ולא מתקבל
  -- מהדפדפן (החלטה 2). אין כאן payment_status — אין תשלום במערכת (§16).
  package_days          smallint,
  package_price_shown   numeric(10,2),
  screening_selected    boolean not null default false,
  terms_version         text,
  terms_accepted_at     timestamptz,

  -- שכבה ב' — נתוני עבודה
  internal_title        text,
  clinic_name           text,
  -- קישור אופציונלי לארגון קיים ב-accounts, כמו job.account_link.
  -- רוב הנכסים מגיעים מטופס ציבורי ואינם ארגון מוכר, ולכן nullable.
  -- הקישור הוא לצורכי CRM בלבד: הנתונים שמתפרסמים נלקחים תמיד מהעמודות
  -- כאן ולא מ-accounts, כדי שעדכון ארגון לא ישנה פרסום חי בטעות.
  account_id            bigint references public.accounts(account_id) on delete set null,
  city_id               bigint references public.dict_cities(id),
  region_id             bigint references public.dict_regions(id),
  street                text,
  street_number         text,
  entrance              text,
  floor                 text,
  area_sqm              numeric(8,2) check (area_sqm is null or area_sqm > 0),
  rooms_count           smallint     check (rooms_count  is null or rooms_count  between 0 and 200),
  units_count           smallint     check (units_count  is null or units_count  between 0 and 200),
  years_active          smallint     check (years_active is null or years_active between 0 and 120),
  asset_type            text,
  clinic_type           text,
  location_type         text,
  client_notes          text,

  accessibility_ids      bigint[] not null default '{}',
  premises_feature_ids   bigint[] not null default '{}',
  imaging_equipment_ids  bigint[] not null default '{}',
  equipment_ids          bigint[] not null default '{}',
  service_ids            bigint[] not null default '{}',
  imaging_notes          text,
  equipment_notes        text,
  services_notes         text,

  -- פרטי הלקוח — פרטיים תמיד. לא מתפרסמים בשום תנאי (§31).
  client_name           text,
  client_business_name  text,
  client_phone          text,
  client_phone_norm     text,
  client_whatsapp       text,
  client_email          text,
  client_contact_notes  text,

  -- שכבה ג' — תצורת הפרסום (נערכת באדמין, חבילה C)
  -- Allow-List: שדה מגיע לציבור רק אם המפתח שלו כאן. את מסמנת באדמין.
  -- ברירת המחדל ריקה — כלומר נכס חדש לא חושף כלום עד שתבחרי.
  -- כשעורך הבלוקים ייבנה, הבלוקים יפנו לאותם מפתחות בדיוק.
  published_fields      text[] not null default '{}',
  -- שמור לעורך הבלוקים העתידי. בתבנית הקבועה אינו בשימוש.
  page_config           jsonb not null default '{"version":1,"blocks":[]}'::jsonb,
  card_config           jsonb not null default '{}'::jsonb,
  public_contact        jsonb not null default '{}'::jsonb,
  cta_buttons           jsonb not null default '[]'::jsonb,

  first_published_at    timestamptz,
  ends_at               timestamptz,
  -- החלטה 10: הארכה היא פעולה ידנית. כל שינוי של ends_at נרשם כאן כאובייקט
  -- {old, new, reason, by, at}. אין תשלום, אין הזמנה חדשה, אין אוטומציה.
  period_history        jsonb not null default '[]'::jsonb,
  last_published_at     timestamptz,
  current_version       int not null default 0,

  admin_notes           text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  created_by            uuid,
  updated_by            uuid,
  archived_at           timestamptz,

  constraint hd_asset_code_uq   unique (asset_code),
  constraint hd_asset_code_fmt  check (asset_code ~ '^HD[0-9]{4,}$'),
  constraint hd_asset_source_ck check (source in ('public_form','manual')),
  constraint hd_asset_wf_ck     check (workflow_status in
        ('new','in_progress','waiting_material','ready','archived')),
  constraint hd_asset_pub_ck    check (publication_state in
        ('draft','published','removed','expired')),
  -- asset_type הוא רשימה נפרדת ולא dict_account_types הקיים, בכוונה:
  -- dict_account_types עונה "איזה סוג ארגון זה" (15 ערכים, כולל יזם,
  -- קופת חולים וספק ציוד) ואילו כאן השאלה היא "מה מוצע". הוא גם לא יכול
  -- לבטא "חדר טיפול", שאינו ארגון אלא יחידה בתוך אחד.
  constraint hd_asset_type_ck   check (asset_type is null or asset_type in
        ('clinic_full','treatment_room','lab','imaging_center','business','other')),
  constraint hd_asset_ctype_ck  check (clinic_type is null or clinic_type in ('private','corporate','other')),
  constraint hd_asset_loc_ck    check (location_type is null or location_type in
        ('residential','office_building','mall','medical_center','other')),
  -- החלטה 11: אין נכס בלי תקופת פרסום, גם כשנוצר ידנית
  constraint hd_asset_pkg_ck    check (package_days is null or package_days in (60,90)),
  constraint hd_asset_win_ck    check (ends_at is null or first_published_at is not null)
);

create index if not exists hd_assets_wf_idx     on public.dental_assets (workflow_status, created_at desc);
create index if not exists hd_assets_pub_idx    on public.dental_assets (publication_state, created_at desc);
create index if not exists hd_assets_city_idx   on public.dental_assets (city_id);
create index if not exists hd_assets_acct_idx   on public.dental_assets (account_id) where account_id is not null;
create index if not exists hd_assets_ends_idx   on public.dental_assets (ends_at) where publication_state = 'published';
create index if not exists hd_assets_phone_idx  on public.dental_assets (client_phone_norm);
create unique index if not exists hd_assets_token_uq on public.dental_assets (submission_token)
  where submission_token is not null;

-- עיר → אזור. טריגר קיים בפרויקט, גנרי לחלוטין — שימוש חוזר ולא שכפול.
drop trigger if exists hd_assets_fill_region on public.dental_assets;
create trigger hd_assets_fill_region
  before insert or update of city_id on public.dental_assets
  for each row execute function public.trg_fill_region_from_city_id();

-- הקפאת מקור הלקוח (§41). לא ניתן לאכוף ב-CHECK כי נדרש OLD.
create or replace function public.hd_freeze_submission()
returns trigger language plpgsql
set search_path = '' as $$
begin
  if old.submission_snapshot is not null
     and new.submission_snapshot is distinct from old.submission_snapshot then
    raise exception 'submission_snapshot_is_immutable' using errcode = '42501';
  end if;
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists hd_assets_freeze on public.dental_assets;
create trigger hd_assets_freeze before update on public.dental_assets
  for each row execute function public.hd_freeze_submission();

-- ───────────────────────────────────────────────────────────────────────────
-- 4. dental_asset_offers — מסלולי עסקה (§26–27)
-- ───────────────────────────────────────────────────────────────────────────
create table if not exists public.dental_asset_offers (
  id                uuid primary key default gen_random_uuid(),
  asset_id          uuid not null references public.dental_assets(id) on delete cascade,
  offer_type        text not null,
  price_amount      numeric(12,2) check (price_amount is null or price_amount > 0),
  price_unit        text,
  -- החלטה 4: מלל חופשי שהאדמין כותב. לא סטטוס, לא מנגנון חשיפה.
  price_note        text,
  available_from    date,
  availability_note text,
  days              smallint[] not null default '{}',
  hours             text,
  included_note     text,
  extra_costs_note  text,
  terms_note        text,
  sale_include_ids  bigint[] not null default '{}',
  notes             text,
  sort_order        smallint not null default 1,
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint hd_offer_type_ck check (offer_type in ('sale','rent_monthly','rent_daily','rent_shift')),
  constraint hd_offer_unit_ck check (price_unit is null or price_unit in ('total','per_month','per_day','per_shift')),
  -- מחיר בלי יחידת מחיר אינו תקין
  constraint hd_offer_pair_ck check (price_amount is null or price_unit is not null),
  -- והיחידה חייבת להתאים לסוג העסקה
  constraint hd_offer_match_ck check (price_unit is null or price_unit = case offer_type
        when 'sale' then 'total' when 'rent_monthly' then 'per_month'
        when 'rent_daily' then 'per_day' else 'per_shift' end),
  constraint hd_offer_days_ck  check (days <@ array[0,1,2,3,4,5,6]::smallint[])
);
create index if not exists hd_offers_asset_idx on public.dental_asset_offers (asset_id, sort_order);
drop trigger if exists hd_offers_touch on public.dental_asset_offers;
create trigger hd_offers_touch before update on public.dental_asset_offers
  for each row execute function public.hd_touch_updated_at();

-- ───────────────────────────────────────────────────────────────────────────
-- 5. dental_asset_images (§30, §49–50)
-- ───────────────────────────────────────────────────────────────────────────
create table if not exists public.dental_asset_images (
  id                uuid primary key default gen_random_uuid(),
  asset_id          uuid not null references public.dental_assets(id) on delete cascade,
  private_path      text not null,
  public_path       text,
  original_filename text,
  mime_type         text,
  byte_size         integer,
  width             integer,
  height            integer,
  sort_order        smallint not null,
  is_published      boolean not null default false,
  alt_text          text,
  caption           text,
  -- Focal Point במקום חיתוך אמיתי: אין שירות עיבוד תמונה בפרויקט.
  -- הערך מתורגם ל-object-position בצד הלקוח.
  focal_x           numeric(4,3) not null default 0.5 check (focal_x between 0 and 1),
  focal_y           numeric(4,3) not null default 0.5 check (focal_y between 0 and 1),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  -- החלטה 9: מגבלת 15 חלה על הגשת הלקוח בלבד ונאכפת ב-RPC.
  -- באדמין אין תקרה, ולכן אין כאן CHECK על sort_order מלבד חיוביות.
  constraint hd_img_sort_ck  check (sort_order > 0),
  constraint hd_img_sort_uq  unique (asset_id, sort_order),
  constraint hd_img_priv_uq  unique (private_path),
  -- SQL לא יכול להעתיק אובייקט אחסון. ההעתקה לדלי הציבורי היא פעולת UI,
  -- והאילוץ הזה מכריח שהיא תקרה לפני הסימון לפרסום.
  constraint hd_img_pubpath_ck check (is_published = false or public_path is not null)
);
create index if not exists hd_img_asset_idx on public.dental_asset_images (asset_id, sort_order);
drop trigger if exists hd_img_touch on public.dental_asset_images;
create trigger hd_img_touch before update on public.dental_asset_images
  for each row execute function public.hd_touch_updated_at();

-- ───────────────────────────────────────────────────────────────────────────
-- 6. dental_asset_publications — גרסאות ציבוריות (§63)
--    asset_code מדונורמל בכוונה: ה-view הציבורי לא עושה JOIN לטבלת העבודה.
-- ───────────────────────────────────────────────────────────────────────────
create table if not exists public.dental_asset_publications (
  id             uuid primary key default gen_random_uuid(),
  asset_id       uuid not null references public.dental_assets(id) on delete cascade,
  asset_code     text not null,
  version_number int  not null,
  status         text not null default 'live',
  public_page    jsonb not null,
  public_card    jsonb not null,
  published_at   timestamptz not null default now(),
  expires_at     timestamptz,
  superseded_at  timestamptz,
  published_by   uuid,
  registry_version smallint not null default 1,

  constraint hd_pub_ver_uq    unique (asset_id, version_number),
  constraint hd_pub_ver_pos   check (version_number > 0),
  constraint hd_pub_status_ck check (status in ('live','superseded','removed','expired')),
  constraint hd_pub_code_fmt  check (asset_code ~ '^HD[0-9]{4,}$'),
  constraint hd_pub_super_ck  check (status <> 'superseded' or superseded_at is not null)
);
-- גרסה חיה אחת לכל נכס
create unique index if not exists hd_pub_live_uq on public.dental_asset_publications (asset_id)
  where status = 'live';
create index if not exists hd_pub_code_idx  on public.dental_asset_publications (asset_code) where status = 'live';
create index if not exists hd_pub_board_idx on public.dental_asset_publications (published_at desc) where status = 'live';
-- ⚠️ אסור להוסיף now() לתנאי אינדקס חלקי — now() אינו IMMUTABLE ו-Postgres
--    ידחה את האינדקס. הטריות חיה ב-WHERE של ה-view וב-RLS בלבד.

-- ───────────────────────────────────────────────────────────────────────────
-- 7. dental_asset_inquiries — לידים פשוטים (§67–70)
--    אין contract_signed_at, אין contract_amount, אין success_fee. (§17)
-- ───────────────────────────────────────────────────────────────────────────
create table if not exists public.dental_asset_inquiries (
  id             uuid primary key default gen_random_uuid(),
  asset_id       uuid not null references public.dental_assets(id) on delete cascade,
  asset_code     text not null,
  offer_id       uuid references public.dental_asset_offers(id) on delete set null,
  offer_label    text,
  publication_id uuid references public.dental_asset_publications(id) on delete set null,
  name           text not null,
  phone          text not null,
  phone_norm     text,
  email          text,
  message        text,
  status         text not null default 'new',
  internal_note  text,
  source_url     text,
  consent        boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint hd_inq_status_ck check (status in
        ('new','in_progress','forwarded','waiting','closed','irrelevant'))
);
create index if not exists hd_inq_asset_idx  on public.dental_asset_inquiries (asset_id, created_at desc);
create index if not exists hd_inq_status_idx on public.dental_asset_inquiries (status, created_at desc);
create index if not exists hd_inq_phone_idx  on public.dental_asset_inquiries (phone_norm);
drop trigger if exists hd_inq_touch on public.dental_asset_inquiries;
create trigger hd_inq_touch before update on public.dental_asset_inquiries
  for each row execute function public.hd_touch_updated_at();

-- ───────────────────────────────────────────────────────────────────────────
-- 8. היסטוריית הארכות — עמודה, לא טבלה.
--    לוג בנפח זעום שנקרא תמיד יחד עם הנכס. טבלה נפרדת הייתה מוסיפה join
--    בלי שום תמורה. העמודה period_history מוגדרת ב-dental_assets למעלה.
-- ───────────────────────────────────────────────────────────────────────────

-- ───────────────────────────────────────────────────────────────────────────
-- 9. תצוגות
-- ───────────────────────────────────────────────────────────────────────────

-- ה-view הציבורי. security_invoker=true — הדפוס של v_cms_published_pages.
-- ⚠️ לא לחקות את v_job_public: הוא security_definer והלינטר מסמן ERROR.
-- ה-WHERE כאן הוא הדבר היחיד שמייצר ציבוריות; פקיעה קורית בלי cron.
create or replace view public.v_dental_asset_public
with (security_invoker = true) as
select p.asset_code, p.version_number, p.public_card, p.public_page,
       p.published_at, p.expires_at
from public.dental_asset_publications p
where p.status = 'live'
  and p.published_at <= now()
  and (p.expires_at is null or p.expires_at > now());

-- view האדמין. days_remaining חייב להיות ביטוי ולא GENERATED — now() אינו IMMUTABLE.
create or replace view public.v_dental_assets_admin
with (security_invoker = true) as
select a.id, a.asset_code, a.internal_title, a.clinic_name, a.asset_type,
       a.workflow_status, a.publication_state,
       a.package_days, a.screening_selected,
       a.city_id, c.name as city_name, a.region_id, r.name as region_name,
       a.account_id, acc.account_name,
       a.created_at, a.first_published_at, a.ends_at, a.current_version,
       (select string_agg(o.offer_type, ',' order by o.sort_order)
          from public.dental_asset_offers o where o.asset_id = a.id and o.is_active) as offer_types,
       (select count(*) from public.dental_asset_inquiries i
         where i.asset_id = a.id and i.status = 'new') as new_inquiries,
       (select count(*) from public.dental_asset_inquiries i where i.asset_id = a.id) as total_inquiries,
       case when a.ends_at is null then null
            else greatest(0, ceil(extract(epoch from (a.ends_at - now())) / 86400))::int
       end as days_remaining
from public.dental_assets a
left join public.dict_cities  c   on c.id = a.city_id
left join public.dict_regions r   on r.id = a.region_id
left join public.accounts     acc on acc.account_id = a.account_id;

-- ───────────────────────────────────────────────────────────────────────────
-- 10. RPC ציבורי — הגשת נכס
--     קריאה אחת. התמונות עולות לדלי הפרטי לפני הקריאה, בדיוק כמו
--     ApplyModal עם candidate-cvs; אין צורך בשורת טיוטה ואין upload-token RPC.
--     קודי השגיאה אינם תת-מחרוזות זה של זה — הממפה בפרונט עושה includes().
-- ───────────────────────────────────────────────────────────────────────────
create or replace function public.submit_public_dental_asset(
  p_submission_token uuid,
  p_client_name text, p_client_business_name text, p_client_phone text,
  p_client_whatsapp text, p_client_email text, p_client_contact_notes text,
  p_clinic_name text, p_city_id bigint, p_street text, p_street_number text,
  p_entrance text, p_floor text, p_area_sqm numeric, p_rooms_count smallint,
  p_units_count smallint, p_years_active smallint, p_asset_type text,
  p_clinic_type text, p_location_type text, p_client_notes text,
  p_accessibility_ids bigint[], p_premises_feature_ids bigint[],
  p_imaging_equipment_ids bigint[], p_equipment_ids bigint[], p_service_ids bigint[],
  p_imaging_notes text, p_equipment_notes text, p_services_notes text,
  p_offers jsonb, p_images jsonb,
  p_package_days smallint, p_screening boolean, p_terms_version text,
  p_terms_accepted boolean, p_source_page text, p_source_url text
) returns table (status text, asset_code text, asset_id uuid)
language plpgsql security definer
set search_path = '' as $$
declare
  v_id uuid; v_code text; v_phone text; v_o jsonb; v_i jsonb; v_n int;
begin
  if coalesce(p_terms_accepted, false) is not true then
    raise exception 'terms_were_not_accepted';
  end if;
  if nullif(btrim(coalesce(p_client_name, '')), '') is null then
    raise exception 'client_name_is_missing';
  end if;

  v_phone := public.normalize_il_mobile_phone(p_client_phone);
  if v_phone is null then
    raise exception 'client_phone_is_invalid';
  end if;

  if p_package_days is null or p_package_days not in (60, 90) then
    raise exception 'package_days_invalid';
  end if;
  if p_city_id is null or not exists (select 1 from public.dict_cities d where d.id = p_city_id) then
    raise exception 'city_was_not_found';
  end if;
  if p_asset_type is null then
    raise exception 'asset_type_missing';
  end if;

  -- מניעת הגשה כפולה בטעות (רענון / לחיצה כפולה)
  if exists (select 1 from public.dental_assets a
              where a.client_phone_norm = v_phone
                and a.city_id = p_city_id
                and a.created_at > now() - interval '12 hours') then
    raise exception 'duplicate_recent_request';
  end if;

  -- כל מזהה מילון חייב להיות קיים ופעיל. עם טבלה אחת זו בדיקה אחת
  -- במקום שש; עם שש טבלאות ויתרתי עליה לגמרי.
  if exists (
    select 1 from unnest(
      coalesce(p_accessibility_ids,'{}') || coalesce(p_premises_feature_ids,'{}') ||
      coalesce(p_imaging_equipment_ids,'{}') || coalesce(p_equipment_ids,'{}') ||
      coalesce(p_service_ids,'{}')) u(oid)
    where not exists (select 1 from public.dict_dental_options d
                       where d.id = u.oid and d.is_active)
  ) then
    raise exception 'unknown_dictionary_id';
  end if;

  if p_offers is null or jsonb_array_length(p_offers) = 0 then
    raise exception 'offers_list_is_empty';
  end if;

  v_n := coalesce(jsonb_array_length(p_images), 0);
  if v_n > 15 then
    raise exception 'too_many_images';   -- החלטה 9: 15 להגשת הלקוח בלבד
  end if;

  -- כל נתיב תמונה חייב לשבת תחת ה-token שנשלח, אחרת אפשר לצרף קובץ זר
  if p_images is not null then
    for v_i in select * from jsonb_array_elements(p_images) loop
      if (v_i ->> 'private_path') is null
         or position((p_submission_token::text || '/') in (v_i ->> 'private_path')) <> 1 then
        raise exception 'image_path_outside_token';
      end if;
    end loop;
  end if;

  insert into public.dental_assets (
    source, submission_token, source_page, source_url,
    workflow_status, publication_state,
    package_days, package_price_shown, screening_selected,
    terms_version, terms_accepted_at,                      -- ← now(), לא מהלקוח
    clinic_name, city_id, street, street_number, entrance, floor,
    area_sqm, rooms_count, units_count, years_active,
    asset_type, clinic_type, location_type, client_notes,
    accessibility_ids, premises_feature_ids, imaging_equipment_ids,
    equipment_ids, service_ids, imaging_notes, equipment_notes, services_notes,
    client_name, client_business_name, client_phone, client_phone_norm,
    client_whatsapp, client_email, client_contact_notes,
    internal_title, submission_snapshot
  ) values (
    'public_form', p_submission_token,
    nullif(btrim(coalesce(p_source_page,'')),''), nullif(btrim(coalesce(p_source_url,'')),''),
    'new', 'draft',
    p_package_days, case p_package_days when 60 then 700 else 800 end, coalesce(p_screening,false),
    p_terms_version, now(),
    nullif(btrim(coalesce(p_clinic_name,'')),''), p_city_id,
    nullif(btrim(coalesce(p_street,'')),''), nullif(btrim(coalesce(p_street_number,'')),''),
    nullif(btrim(coalesce(p_entrance,'')),''), nullif(btrim(coalesce(p_floor,'')),''),
    p_area_sqm, p_rooms_count, p_units_count, p_years_active,
    p_asset_type, p_clinic_type, p_location_type, nullif(btrim(coalesce(p_client_notes,'')),''),
    coalesce(p_accessibility_ids,'{}'), coalesce(p_premises_feature_ids,'{}'),
    coalesce(p_imaging_equipment_ids,'{}'), coalesce(p_equipment_ids,'{}'),
    coalesce(p_service_ids,'{}'),
    nullif(btrim(coalesce(p_imaging_notes,'')),''), nullif(btrim(coalesce(p_equipment_notes,'')),''),
    nullif(btrim(coalesce(p_services_notes,'')),''),
    btrim(p_client_name), nullif(btrim(coalesce(p_client_business_name,'')),''),
    btrim(p_client_phone), v_phone,
    nullif(btrim(coalesce(p_client_whatsapp,'')),''), lower(nullif(btrim(coalesce(p_client_email,'')),'')),
    nullif(btrim(coalesce(p_client_contact_notes,'')),''),
    coalesce(nullif(btrim(coalesce(p_clinic_name,'')),''), 'נכס חדש'),
    jsonb_build_object(
      'received_at', now(),
      'client', jsonb_build_object('name',p_client_name,'business',p_client_business_name,
                 'phone',p_client_phone,'whatsapp',p_client_whatsapp,'email',p_client_email,
                 'notes',p_client_contact_notes),
      'asset', jsonb_build_object('clinic_name',p_clinic_name,'city_id',p_city_id,'street',p_street,
                 'street_number',p_street_number,'entrance',p_entrance,'floor',p_floor,
                 'area_sqm',p_area_sqm,'rooms_count',p_rooms_count,'units_count',p_units_count,
                 'years_active',p_years_active,'asset_type',p_asset_type,'clinic_type',p_clinic_type,
                 'location_type',p_location_type,'notes',p_client_notes),
      'dicts', jsonb_build_object('accessibility',p_accessibility_ids,'premises',p_premises_feature_ids,
                 'imaging',p_imaging_equipment_ids,'equipment',p_equipment_ids,'services',p_service_ids,
                 'imaging_notes',p_imaging_notes,'equipment_notes',p_equipment_notes,
                 'services_notes',p_services_notes),
      'offers', p_offers,
      'images', p_images,
      'service', jsonb_build_object('package_days',p_package_days,'screening',p_screening,
                 'terms_version',p_terms_version)
    )
  ) returning id, asset_code into v_id, v_code;

  -- מסלולי עסקה
  for v_o in select * from jsonb_array_elements(p_offers) loop
    if (v_o ->> 'offer_type') not in ('sale','rent_monthly','rent_daily','rent_shift') then
      raise exception 'offer_type_is_invalid';
    end if;
    insert into public.dental_asset_offers (
      asset_id, offer_type, price_amount, price_unit, available_from,
      availability_note, days, hours, included_note, extra_costs_note,
      terms_note, sale_include_ids, notes, sort_order
    ) values (
      v_id, v_o ->> 'offer_type',
      nullif(v_o ->> 'price_amount','')::numeric,
      case when nullif(v_o ->> 'price_amount','') is null then null
           else case v_o ->> 'offer_type'
                  when 'sale' then 'total' when 'rent_monthly' then 'per_month'
                  when 'rent_daily' then 'per_day' else 'per_shift' end end,
      nullif(v_o ->> 'available_from','')::date,
      nullif(btrim(coalesce(v_o ->> 'availability_note','')),''),
      coalesce((select array_agg(x::smallint) from jsonb_array_elements_text(
                  coalesce(v_o -> 'days','[]'::jsonb)) t(x)), '{}'),
      nullif(btrim(coalesce(v_o ->> 'hours','')),''),
      nullif(btrim(coalesce(v_o ->> 'included_note','')),''),
      nullif(btrim(coalesce(v_o ->> 'extra_costs_note','')),''),
      nullif(btrim(coalesce(v_o ->> 'terms_note','')),''),
      coalesce((select array_agg(x::bigint) from jsonb_array_elements_text(
                  coalesce(v_o -> 'sale_include_ids','[]'::jsonb)) t(x)), '{}'),
      nullif(btrim(coalesce(v_o ->> 'notes','')),''),
      coalesce(nullif(v_o ->> 'sort_order','')::smallint, 1)
    );
  end loop;

  -- תמונות — נכנסות פרטיות ולא מסומנות לפרסום (§30)
  if p_images is not null then
    v_n := 0;
    for v_i in select * from jsonb_array_elements(p_images) loop
      v_n := v_n + 1;
      insert into public.dental_asset_images (
        asset_id, private_path, original_filename, mime_type, byte_size, sort_order, is_published
      ) values (
        v_id, v_i ->> 'private_path',
        nullif(v_i ->> 'original_filename',''), nullif(v_i ->> 'mime_type',''),
        nullif(v_i ->> 'byte_size','')::int, v_n::smallint, false
      );
    end loop;
  end if;

  return query select 'success'::text, v_code, v_id;
end $$;

-- ───────────────────────────────────────────────────────────────────────────
-- 11. RPC ציבורי — השארת פרטים (§68)
--     מאתר את הנכס דרך הפרסום החי בלבד. אחרת אפשר לפנות לנכס שלא פורסם
--     ולגלות קודי HD תקפים לפי הבדל בשגיאה.
-- ───────────────────────────────────────────────────────────────────────────
create or replace function public.submit_dental_asset_inquiry(
  p_asset_code text, p_offer_id uuid, p_name text, p_phone text,
  p_email text, p_message text, p_source_url text, p_consent boolean
) returns table (status text, inquiry_id uuid)
language plpgsql security definer
set search_path = '' as $$
declare
  v_asset uuid; v_pub uuid; v_code text; v_phone text; v_label text; v_id uuid;
begin
  if coalesce(p_consent, false) is not true then
    raise exception 'consent_was_not_given';
  end if;
  if nullif(btrim(coalesce(p_name,'')), '') is null then
    raise exception 'lead_name_is_missing';
  end if;

  v_phone := public.normalize_il_mobile_phone(p_phone);
  if v_phone is null then
    raise exception 'lead_phone_is_invalid';
  end if;

  select p.asset_id, p.id, p.asset_code into v_asset, v_pub, v_code
  from public.dental_asset_publications p
  where p.asset_code = upper(btrim(p_asset_code))
    and p.status = 'live'
    and p.published_at <= now()
    and (p.expires_at is null or p.expires_at > now());
  if not found then
    raise exception 'asset_is_not_published';
  end if;

  if p_offer_id is not null then
    select case o.offer_type
             when 'sale' then 'מכירה' when 'rent_monthly' then 'שכירות חודשית'
             when 'rent_daily' then 'השכרה יומית' else 'השכרה לפי משמרת' end
      into v_label
    from public.dental_asset_offers o where o.id = p_offer_id and o.asset_id = v_asset;
    if v_label is null then
      raise exception 'offer_not_on_this_asset';
    end if;
  end if;

  if exists (select 1 from public.dental_asset_inquiries i
              where i.asset_id = v_asset and i.phone_norm = v_phone
                and i.created_at > now() - interval '12 hours') then
    raise exception 'duplicate_recent_lead';
  end if;

  insert into public.dental_asset_inquiries
    (asset_id, asset_code, offer_id, offer_label, publication_id,
     name, phone, phone_norm, email, message, source_url, consent)
  values
    (v_asset, v_code, p_offer_id, v_label, v_pub,
     btrim(p_name), btrim(p_phone), v_phone,
     lower(nullif(btrim(coalesce(p_email,'')),'')),
     nullif(btrim(coalesce(p_message,'')),''),
     nullif(btrim(coalesce(p_source_url,'')),''), true)
  returning id into v_id;

  return query select 'success'::text, v_id;
end $$;


-- ───────────────────────────────────────────────────────────────────────────
-- 15. בניית התוכן הציבורי — הפונקציה המרכזית.
--     בונה payload מהנתונים המאושרים בלבד. שדה נכנס רק אם המפתח שלו
--     ב-published_fields; תמונה רק אם is_published; מסלול רק אם is_active.
--     פרטי הלקוח (client_*) לא נכנסים בשום תנאי — הם לא ברשימת המפתחות
--     ואין להם ענף בקוד. פרטי הקשר הציבוריים נלקחים מ-public_contact בלבד.
-- ───────────────────────────────────────────────────────────────────────────
create or replace function public.hd_build_publication_payload(p_asset_id uuid)
returns jsonb language plpgsql stable security definer
set search_path = '' as $fn$
declare
  a           public.dental_assets%rowtype;
  v_city      text;
  v_region    text;
  v_has       boolean;
  v_facts     jsonb := '[]'::jsonb;
  v_offers    jsonb := '[]'::jsonb;
  v_images    jsonb := '[]'::jsonb;
  v_groups    jsonb := '{}'::jsonb;
  v_cover     jsonb;
  v_card      jsonb;
  v_page      jsonb;
  r           record;
begin
  select * into a from public.dental_assets where id = p_asset_id;
  if not found then raise exception 'asset_was_not_found'; end if;

  select c.name into v_city   from public.dict_cities  c where c.id = a.city_id;
  select g.name into v_region from public.dict_regions g where g.id = a.region_id;

  -- נתוני מפתח — רק מפתחות שסומנו
  v_has := 'area_sqm' = any(a.published_fields);
  if v_has and a.area_sqm is not null then
    v_facts := v_facts || jsonb_build_object('key','area_sqm','label','שטח','value',a.area_sqm,'unit','מ״ר');
  end if;
  if 'rooms_count' = any(a.published_fields) and a.rooms_count is not null then
    v_facts := v_facts || jsonb_build_object('key','rooms_count','label','חדרי טיפול','value',a.rooms_count);
  end if;
  if 'units_count' = any(a.published_fields) and a.units_count is not null then
    v_facts := v_facts || jsonb_build_object('key','units_count','label','יוניטים','value',a.units_count);
  end if;
  if 'years_active' = any(a.published_fields) and a.years_active is not null then
    v_facts := v_facts || jsonb_build_object('key','years_active','label','ותק','value',a.years_active,'unit','שנים');
  end if;

  -- קבוצות ציוד — שמות מהמילון, לא מזהים
  for r in
    select k.key, k.label, k.ids from (values
        ('accessibility','נגישות וסביבה', a.accessibility_ids),
        ('premises','מה קיים בנכס',       a.premises_feature_ids),
        ('imaging','ציוד דימות',          a.imaging_equipment_ids),
        ('equipment','ציוד ומכשור',       a.equipment_ids),
        ('services','שירותים ותשתיות',    a.service_ids)
      ) as k(key,label,ids)
  loop
    if r.key = any(a.published_fields) and coalesce(array_length(r.ids,1),0) > 0 then
      v_groups := v_groups || jsonb_build_object(r.key, jsonb_build_object(
        'label', r.label,
        'items', coalesce((select jsonb_agg(d.name order by d.sort_order)
                             from public.dict_dental_options d where d.id = any(r.ids)), '[]'::jsonb)));
    end if;
  end loop;
  if 'imaging' = any(a.published_fields) and a.imaging_notes is not null then
    v_groups := jsonb_set(v_groups, '{imaging,note}', to_jsonb(a.imaging_notes), true);
  end if;
  if 'equipment' = any(a.published_fields) and a.equipment_notes is not null then
    v_groups := jsonb_set(v_groups, '{equipment,note}', to_jsonb(a.equipment_notes), true);
  end if;
  if 'services' = any(a.published_fields) and a.services_notes is not null then
    v_groups := jsonb_set(v_groups, '{services,note}', to_jsonb(a.services_notes), true);
  end if;

  -- מסלולי עסקה פעילים בלבד
  select coalesce(jsonb_agg(jsonb_build_object(
           'id', o.id, 'offer_type', o.offer_type,
           'price_amount', case when 'price' = any(a.published_fields) then o.price_amount end,
           'price_unit',   case when 'price' = any(a.published_fields) then o.price_unit end,
           'price_note',   o.price_note,
           'available_from',    case when 'availability' = any(a.published_fields) then o.available_from end,
           'availability_note', case when 'availability' = any(a.published_fields) then o.availability_note end,
           'days',  case when 'days'  = any(a.published_fields) then to_jsonb(o.days) end,
           'hours', case when 'hours' = any(a.published_fields) then o.hours end,
           'included_note',    case when 'included'    = any(a.published_fields) then o.included_note end,
           'extra_costs_note', case when 'extra_costs' = any(a.published_fields) then o.extra_costs_note end,
           'terms_note',       case when 'terms'       = any(a.published_fields) then o.terms_note end,
           'sale_includes', case when 'included' = any(a.published_fields) then
              coalesce((select jsonb_agg(d.name order by d.sort_order)
                          from public.dict_dental_options d where d.id = any(o.sale_include_ids)), '[]'::jsonb) end
         ) order by o.sort_order), '[]'::jsonb)
    into v_offers
  from public.dental_asset_offers o
  where o.asset_id = p_asset_id and o.is_active;

  -- תמונות שסומנו לפרסום בלבד
  select coalesce(jsonb_agg(jsonb_build_object(
           'path', i.public_path, 'alt', i.alt_text, 'caption', i.caption,
           'focal_x', i.focal_x, 'focal_y', i.focal_y) order by i.sort_order), '[]'::jsonb)
    into v_images
  from public.dental_asset_images i
  where i.asset_id = p_asset_id and i.is_published and i.public_path is not null;

  v_cover := coalesce(v_images -> 0, 'null'::jsonb);

  v_card := jsonb_strip_nulls(jsonb_build_object(
    'asset_code',   a.asset_code,
    'title',        a.card_config ->> 'title',
    'location',     coalesce(a.card_config ->> 'location', v_city),
    'type_label',   a.card_config ->> 'type_label',
    'excerpt',      a.card_config ->> 'excerpt',
    'highlights',   a.card_config -> 'highlights',
    'tags',         a.card_config -> 'tags',
    'image',        coalesce(a.card_config -> 'image', v_cover),
    'offer_types',  (select coalesce(jsonb_agg(distinct o.offer_type), '[]'::jsonb)
                       from public.dental_asset_offers o
                      where o.asset_id = p_asset_id and o.is_active)));

  v_page := jsonb_strip_nulls(jsonb_build_object(
    'asset_code',  a.asset_code,
    'template',    'fixed_v1',
    'title',       a.card_config ->> 'public_title',
    'subtitle',    a.card_config ->> 'public_subtitle',
    'description', a.card_config ->> 'public_description',
    'clinic_name', case when 'clinic_name' = any(a.published_fields) then a.clinic_name end,
    'asset_type',  case when 'asset_type'  = any(a.published_fields) then a.asset_type end,
    'clinic_type', case when 'clinic_type' = any(a.published_fields) then a.clinic_type end,
    'location', jsonb_strip_nulls(jsonb_build_object(
       'city',   case when 'city'   = any(a.published_fields) then v_city end,
       'region', case when 'region' = any(a.published_fields) then v_region end,
       'street', case when 'street' = any(a.published_fields) then a.street end,
       'street_number', case when 'street_number' = any(a.published_fields) then a.street_number end,
       'floor',    case when 'floor'    = any(a.published_fields) then a.floor end,
       'entrance', case when 'entrance' = any(a.published_fields) then a.entrance end,
       'label',    a.card_config ->> 'location')),
    'facts',   v_facts,
    'groups',  v_groups,
    'offers',  v_offers,
    'images',  v_images,
    'contact', a.public_contact,     -- מה שהוזן באדמין. לא נשאב מ-client_*
    'ctas',    a.cta_buttons,
    'seo', jsonb_strip_nulls(jsonb_build_object(
       'og_title',       coalesce(a.card_config ->> 'og_title',       a.card_config ->> 'title'),
       'og_description', coalesce(a.card_config ->> 'og_description', a.card_config ->> 'excerpt'),
       'og_image',       coalesce(a.card_config ->> 'og_image',       v_cover ->> 'path')))));

  -- רשת ביטחון: אם מפתח פרטי הצליח להיכנס, הפרסום נכשל ולא יוצא לאוויר
  if v_page::text ~ '(client_phone|client_email|client_name|client_whatsapp|admin_notes|private_path|submission_snapshot|internal_title)' then
    raise exception 'payload_contains_private_key' using errcode = '42501';
  end if;

  return jsonb_build_object('page', v_page, 'card', v_card);
end $fn$;

-- ───────────────────────────────────────────────────────────────────────────
-- 16. שער הפרסום — חוסם רק מה שישבור את התצוגה (החלטה 8).
--     אין מחיר, אין טלפון, אין Waze, אין ציוד — לא חוסם.
-- ───────────────────────────────────────────────────────────────────────────
create or replace function public.hd_publish_gate(p_asset_id uuid)
returns void language plpgsql stable
set search_path = '' as $fn$
declare a public.dental_assets%rowtype;
begin
  select * into a from public.dental_assets where id = p_asset_id;
  if not found then raise exception 'asset_was_not_found'; end if;

  if nullif(btrim(coalesce(a.card_config ->> 'title','')), '') is null then
    raise exception 'public_title_is_empty';
  end if;
  if not exists (select 1 from public.dental_asset_images i
                  where i.asset_id = p_asset_id and i.is_published and i.public_path is not null) then
    raise exception 'no_published_image';
  end if;
  if exists (select 1 from public.dental_asset_images i
              where i.asset_id = p_asset_id and i.is_published and i.public_path is null) then
    raise exception 'image_copy_is_pending';
  end if;
  if coalesce(array_length(a.published_fields,1),0) = 0
     and not exists (select 1 from public.dental_asset_offers o
                      where o.asset_id = p_asset_id and o.is_active) then
    raise exception 'nothing_selected_for_publishing';
  end if;
end $fn$;

-- ───────────────────────────────────────────────────────────────────────────
-- 17. תצוגה מקדימה — אותה פונקציית בנייה, בלי כתיבה.
--     לכן מה שנראה ב-Preview הוא בדיוק מה שיפורסם.
-- ───────────────────────────────────────────────────────────────────────────
create or replace function public.preview_dental_asset(p_asset_id uuid)
returns jsonb language plpgsql stable security definer
set search_path = '' as $fn$
begin
  if (select auth.uid()) is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  return public.hd_build_publication_payload(p_asset_id);
end $fn$;

-- ───────────────────────────────────────────────────────────────────────────
-- 18. פרסום · עדכון · הסרה · הארכה
-- ───────────────────────────────────────────────────────────────────────────
create or replace function public.publish_dental_asset(p_asset_id uuid)
returns jsonb language plpgsql security definer
set search_path = '' as $fn$
declare a public.dental_assets%rowtype; v jsonb; v_ends timestamptz; v_ver int;
begin
  if (select auth.uid()) is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  select * into a from public.dental_assets where id = p_asset_id for update;
  if not found then raise exception 'asset_was_not_found'; end if;
  if a.package_days is null then raise exception 'package_days_invalid'; end if;

  perform public.hd_publish_gate(p_asset_id);
  v := public.hd_build_publication_payload(p_asset_id);

  -- השעון מתחיל בפרסום הראשון בפועל, ולא מתאפס בעדכונים (§61)
  v_ends := coalesce(a.ends_at, now() + make_interval(days => a.package_days));

  update public.dental_asset_publications
     set status = 'superseded', superseded_at = now()
   where asset_id = p_asset_id and status = 'live';

  select coalesce(max(version_number),0)+1 into v_ver
    from public.dental_asset_publications where asset_id = p_asset_id;

  insert into public.dental_asset_publications
    (asset_id, asset_code, version_number, status, public_page, public_card,
     published_at, expires_at, published_by)
  values (p_asset_id, a.asset_code, v_ver, 'live', v -> 'page', v -> 'card',
          now(), v_ends, (select auth.uid()));

  update public.dental_assets
     set publication_state  = 'published',
         first_published_at = coalesce(first_published_at, now()),
         ends_at            = v_ends,
         last_published_at  = now(),
         current_version    = v_ver,
         workflow_status    = case when workflow_status = 'archived' then workflow_status else 'ready' end
   where id = p_asset_id;

  return jsonb_build_object('status','published','version',v_ver,'ends_at',v_ends);
end $fn$;

-- Publish Update — אותה פונקציה. גרסה חדשה, אותו שעון.
create or replace function public.publish_dental_asset_update(p_asset_id uuid)
returns jsonb language plpgsql security definer
set search_path = '' as $fn$
begin
  if (select auth.uid()) is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if not exists (select 1 from public.dental_asset_publications
                  where asset_id = p_asset_id and status = 'live') then
    raise exception 'no_live_publication';
  end if;
  return public.publish_dental_asset(p_asset_id);
end $fn$;

create or replace function public.unpublish_dental_asset(p_asset_id uuid, p_reason text default null)
returns jsonb language plpgsql security definer
set search_path = '' as $fn$
begin
  if (select auth.uid()) is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  update public.dental_asset_publications
     set status = 'removed', superseded_at = now()
   where asset_id = p_asset_id and status = 'live';
  update public.dental_assets set publication_state = 'removed' where id = p_asset_id;
  return jsonb_build_object('status','removed');
end $fn$;

-- הארכה ידנית (החלטה 10). אין תשלום, אין הזמנה חדשה, אין אוטומציה.
create or replace function public.extend_dental_asset(
  p_asset_id uuid, p_new_ends_at timestamptz, p_reason text default null)
returns jsonb language plpgsql security definer
set search_path = '' as $fn$
declare v_old timestamptz;
begin
  if (select auth.uid()) is null then raise exception 'not_authenticated' using errcode='42501'; end if;
  if p_new_ends_at is null then raise exception 'new_end_date_missing'; end if;

  select ends_at into v_old from public.dental_assets where id = p_asset_id for update;

  update public.dental_assets
     set ends_at = p_new_ends_at,
         period_history = period_history || jsonb_build_object(
           'old', v_old, 'new', p_new_ends_at, 'reason', p_reason,
           'by', (select auth.uid()), 'at', now())
   where id = p_asset_id;

  update public.dental_asset_publications
     set expires_at = p_new_ends_at
   where asset_id = p_asset_id and status = 'live';

  return jsonb_build_object('status','extended','ends_at',p_new_ends_at);
end $fn$;

-- ───────────────────────────────────────────────────────────────────────────
-- 12. RLS
-- ───────────────────────────────────────────────────────────────────────────
alter table public.dental_assets                enable row level security;
alter table public.dental_asset_offers          enable row level security;
alter table public.dental_asset_images          enable row level security;
alter table public.dental_asset_publications    enable row level security;
alter table public.dental_asset_inquiries       enable row level security;
alter table public.dict_dental_options          enable row level security;

do $$
declare t text;
begin
  foreach t in array array['dental_assets','dental_asset_offers','dental_asset_images',
                           'dental_asset_inquiries'] loop
    execute format('drop policy if exists hd_auth_all on public.%I', t);
    execute format('create policy hd_auth_all on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;

end $$;

drop policy if exists hd_dict_anon_read on public.dict_dental_options;
create policy hd_dict_anon_read on public.dict_dental_options for select to anon using (true);
drop policy if exists hd_dict_auth_all on public.dict_dental_options;
create policy hd_dict_auth_all on public.dict_dental_options for all to authenticated using (true) with check (true);

-- הפרסומים: anon רואה רק גרסה חיה שלא פגה. אותו תנאי כמו ב-view.
drop policy if exists hd_pub_anon_live   on public.dental_asset_publications;
drop policy if exists hd_pub_auth_select on public.dental_asset_publications;
drop policy if exists hd_pub_auth_write  on public.dental_asset_publications;
create policy hd_pub_anon_live on public.dental_asset_publications for select to anon
  using (status = 'live' and published_at <= now() and (expires_at is null or expires_at > now()));
create policy hd_pub_auth_select on public.dental_asset_publications for select to authenticated using (true);
create policy hd_pub_auth_write  on public.dental_asset_publications for insert to authenticated with check (true);
drop policy if exists hd_pub_auth_update on public.dental_asset_publications;
create policy hd_pub_auth_update on public.dental_asset_publications for update to authenticated using (true) with check (true);
-- אין policy מחיקה: טבלת הפרסומים היא היסטוריה, append-only.

-- ⚠️ ל-anon אין policy על dental_assets / offers / images / inquiries.
--    הכתיבה הציבורית עוברת אך ורק דרך שני ה-RPC למעלה (SECURITY DEFINER).

-- ───────────────────────────────────────────────────────────────────────────
-- 13. הרשאות — הבלוק הקריטי
--     ⚠️ pg_default_acl בפרויקט מעניק ל-anon arwdDxtm על כל טבלה חדשה,
--     EXECUTE על כל פונקציה חדשה ו-nextval על כל sequence חדש.
--     בלי ה-REVOKE הזה, RLS הוא השער היחיד — ומספיקה טעות אחת לדליפה.
-- ───────────────────────────────────────────────────────────────────────────
revoke all on public.dental_assets, public.dental_asset_offers,
              public.dental_asset_images, public.dental_asset_publications,
              public.dental_asset_inquiries, public.dict_dental_options
  from anon, authenticated, public;

revoke all on sequence public.dental_asset_code_seq from anon, authenticated, public;

grant select, insert, update, delete on
  public.dental_assets, public.dental_asset_offers, public.dental_asset_images,
  public.dental_asset_inquiries
  to authenticated;
grant select, insert, update on public.dental_asset_publications to authenticated;

-- anon: קריאת עמודות מותרות בלבד על הפרסומים, ותו לא.
grant select (asset_code, version_number, public_card, public_page, published_at, expires_at, status)
  on public.dental_asset_publications to anon;

-- ⚠️ גם views מקבלים את ברירת המחדל של pg_default_acl. בלי ה-REVOKE הזה
-- anon מקבל SELECT על view האדמין. לא דליפה בפועל (security_invoker חוסם),
-- אבל זו הסתמכות על שער יחיד. נתפס באימות שאחרי ההרצה, 26.08.2026.
revoke all on public.v_dental_asset_public from anon, authenticated, public;
revoke all on public.v_dental_assets_admin from anon, authenticated, public;
grant select on public.v_dental_asset_public to anon, authenticated;
grant select on public.v_dental_assets_admin to authenticated;

grant select on public.dict_dental_options to anon, authenticated;
grant insert, update, delete on public.dict_dental_options to authenticated;

-- פונקציות: השלילה וההענקה לפי oid, לא לפי חתימה שנכתבת ידנית.
-- חתימה בת 36 פרמטרים מוקלדת ידנית היא מקור ודאי לטעות, וכל טעות
-- מפילה את הטרנזקציה. regprocedure מרכיב את החתימה מהקטלוג.
do $$
declare r record;
begin
  for r in select pr.oid::regprocedure as sig
             from pg_proc pr join pg_namespace ns on ns.oid = pr.pronamespace
            where ns.nspname = 'public'
              and pr.proname in ('submit_public_dental_asset','submit_dental_asset_inquiry')
  loop
    execute format('revoke execute on function %s from public', r.sig);
    execute format('grant execute on function %s to anon, authenticated', r.sig);
  end loop;

  -- פונקציות אדמין: authenticated בלבד
  for r in select pr.oid::regprocedure as sig
             from pg_proc pr join pg_namespace ns on ns.oid = pr.pronamespace
            where ns.nspname = 'public'
              and pr.proname in ('preview_dental_asset','publish_dental_asset',
                                 'publish_dental_asset_update','unpublish_dental_asset',
                                 'extend_dental_asset')
  loop
    execute format('revoke execute on function %s from public, anon', r.sig);
    execute format('grant execute on function %s to authenticated', r.sig);
  end loop;

  -- פונקציות פנימיות: אף אחד לא קורא להן ישירות
  for r in select pr.oid::regprocedure as sig
             from pg_proc pr join pg_namespace ns on ns.oid = pr.pronamespace
            where ns.nspname = 'public'
              and pr.proname in ('hd_touch_updated_at','hd_freeze_submission',
                                 'hd_build_publication_payload','hd_publish_gate')
  loop
    execute format('revoke execute on function %s from public, anon, authenticated', r.sig);
  end loop;
end $$;

-- ───────────────────────────────────────────────────────────────────────────
-- 14. אחסון — דלי פרטי להגשות ודלי ציבורי לתמונות שאושרו (§74)
--     anon מעלה ואינו קורא, בדיוק כמו candidate-cvs.
-- ───────────────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('dental-asset-submissions','dental-asset-submissions', false, 10485760,
        array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('dental-assets-public','dental-assets-public', true, 10485760,
        array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

drop policy if exists hd_sub_anon_insert on storage.objects;
create policy hd_sub_anon_insert on storage.objects for insert to anon
  with check (bucket_id = 'dental-asset-submissions');

drop policy if exists hd_sub_auth_all on storage.objects;
create policy hd_sub_auth_all on storage.objects for all to authenticated
  using (bucket_id = 'dental-asset-submissions') with check (bucket_id = 'dental-asset-submissions');

drop policy if exists hd_pubimg_read on storage.objects;
create policy hd_pubimg_read on storage.objects for select to public
  using (bucket_id = 'dental-assets-public');

drop policy if exists hd_pubimg_auth_all on storage.objects;
create policy hd_pubimg_auth_all on storage.objects for all to authenticated
  using (bucket_id = 'dental-assets-public') with check (bucket_id = 'dental-assets-public');

-- ⚠️ הערה לתיעוד: בפרויקט קיימות שלוש policies גורפות
--    (Authenticated can upload / update / delete) עם qual = true ובלי סינון
--    bucket_id. כלומר כל משתמש מחובר יכול למחוק כל אובייקט בכל דלי.
--    זה קדם ל-HOME DENT ואינו בהיקף הזה, אבל שווה ticket נפרד.

commit;

-- ═══════════════════════════════════════════════════════════════════════════
-- אחרי ההרצה: להריץ get_advisors(security) ולוודא אפס לינטים חדשים.
-- דליי האחסון נכללים בקובץ (סעיף 14).
-- ═══════════════════════════════════════════════════════════════════════════
